### PR TITLE
Export rule types

### PR DESCRIPTION
**Pull request by linlinyang**
It useful for define rules

### CODE REVIEW

**Comment by Shinigami92** [comment]
I'm not sure if this is the right place :thinking:  
Should maybe the `@types/eslint` / https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/eslint updated?

**Comment by jerone** [comment]
I was actually looking for this. 
I have some rules that are inherited from ESLint and use the same schema.
Instead of defining my own schema, I rather use the same from ESLint (here).

**Comment by Shinigami92** [comment]
Please tell me which exact interfaces you want to use and why, and why it cant be added to `@types/eslint` itself. Then I will consider it.

**Comment by jerone** [comment]
> Please tell me which exact interfaces you want to use and why, and why it cant be added to `@types/eslint` itself. Then I will consider it.

I want to use the `eol-last` rule schema. 

If I understand it correctly, I cannot use the types from `@types/eslint`, because they are wrapped in their own `Linter.RuleEntry`.

To write a valid rule in my config, I get something like:
```
"my-rule/eol-last": ["error", "error", "always"],
```
(Notice the double `"error"`)

**Comment by linlinyang** [comment]
> I'm not sure if this is the right place 🤔 Should maybe the `@types/eslint` / https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/eslint updated?

**Comment by Shinigami92** [comment]
Here are some example links of how to progress further:

- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68675
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68676
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68677
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68678

Thanks @linlinyang :+1:

**Pull request closed without merging**
